# Generated by Django 2.2.5 on 2019-10-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reCicle.Estado')),
                ('nome_cidade', models.CharField(max_length=30)),
            ],
            bases=('reCicle.estado',),
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reCicle.Usuario')),
                ('habilitacao', models.CharField(max_length=11)),
                ('placa', models.CharField(max_length=7)),
            ],
            bases=('reCicle.usuario',),
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('cidade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reCicle.Cidade')),
                ('nome_bairro', models.CharField(max_length=30)),
            ],
            bases=('reCicle.cidade',),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('bairro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reCicle.Bairro')),
                ('cep', models.CharField(max_length=8)),
                ('numero', models.CharField(max_length=5)),
                ('logradouro', models.CharField(max_length=50)),
                ('referencia', models.TextField()),
            ],
            bases=('reCicle.bairro',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reCicle.Usuario')),
                ('cpf', models.CharField(max_length=11)),
                ('nome_completo', models.TextField()),
                ('tefefone', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reCicle.Endereco')),
            ],
            bases=('reCicle.usuario',),
        ),
    ]
