# Generated by Django 2.2.6 on 2019-10-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.Endereco'),
            preserve_default=False,
        ),
    ]
