# Generated by Django 2.2.5 on 2019-10-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome_completo',
            field=models.TextField(default="None"),
            preserve_default=False,
        ),
    ]
