# Generated by Django 2.2.5 on 2019-10-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresareciclagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresareciclagem',
            old_name='tefefone',
            new_name='telefone',
        ),
    ]
