# Generated by Django 2.2.5 on 2019-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('cpf', models.CharField(max_length=11)),
                ('placa', models.CharField(max_length=8)),
                ('habilitacao', models.CharField(max_length=11)),
                ('nada_consta', models.BooleanField()),
            ],
        ),
    ]
