# Generated by Django 2.2.5 on 2019-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='dt_nascimento',
            field=models.DateField(null=True),
        ),
    ]
